version: '3.3'

volumes:
  pg_data:
  static_files:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  tester:
    build: tester/
    env_file: .env
    depends_on:
      - db
    restart: on-failure:2
    volumes:
      - static_files:/app/staticfiles/
    command: >
      bash -c "python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py collectstatic --no-input
      && python manage.py load_tests
      && gunicorn --bind 0.0.0.0:8000 tester.wsgi"

  nginx:
    depends_on:
        - tester
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/tester.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_files:/static