# Generated by Django 4.2.7 on 2023-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="questions",
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="used_in_tests",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="questions",
                to="test_app.test",
                verbose_name="Used in tests",
            ),
        ),
    ]
