# Generated by Django 4.2.7 on 2023-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "test_app",
            "0002_remove_test_questions_questionanswer_used_in_tests",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="used_in_tests",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                to="test_app.test",
                verbose_name="Used in tests",
            ),
        ),
    ]
