# Generated by Django 4.2.7 on 2023-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_remove_questionanswer_used_in_tests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="test_complete",
            field=models.BooleanField(
                default=False, verbose_name="Is test complete?"
            ),
        ),
    ]
